default_platform(:ios)

platform :ios do
  desc "firebase에 배포하는 fastlane"
  lane :distribution_firebase do
    increment_build_number
    git_commit(path: "./Cproject.xcodeproj/project.pbxproj", message: "버전 올림")
    # push_to_git_remote
    build_app(
	scheme: "Release",
	export_method: "app-store"
    )
    firebase_app_distribution(
            app: "1:940149019082:ios:0234766b317971ea0a7f33",
            testers: ""
    )
  end

  desc "build test"
  lane :build_test do
    build_app(
	scheme: "Release",
	export_method: "app-store"
    )
  end
end
