name: firebase distribution

on:
  push:
    branches: [ "Distribution" ]

jobs:
  build:
    name: Build and Test default scheme using any available iPhone simulator
    runs-on: macOS

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: firebase distribution
        run: |
          fastlane distribution_firebase
